var TRACKS={
iphone:{key:"35-iris-iphone-v2",nextC:"Stop. Remove the unknown device / profile / linked session YOURSELF. Change Apple ID password on this phone.",qs:[
{id:"devices",q:"Apple ID -> Devices: a phone, iPad, or Mac you do not own?",path:"Settings -> [your name] -> Devices",yes:"C"},
{id:"mdm",q:"A configuration profile or MDM you did not install?",path:"Settings -> General -> VPN & Device Management",yes:"C"},
{id:"ext",q:"A Safari extension you do not remember installing?",path:"Settings -> Apps -> Safari -> Extensions",yes:"B"},
{id:"chat",q:"A second phone or browser linked to WhatsApp / iMessage / Telegram?",path:"WhatsApp -> Settings -> Linked devices",yes:"C"},
{id:"mail",q:"Mail forwarding or a filter you did not set?",path:"Gmail / iCloud Mail filters. Look only.",yes:"C"},
{id:"screen",q:"Screen Sharing or a remote-view app you did not turn on?",path:"Settings -> Screen Time -> unknown apps",yes:"C"},
{id:"shareplay",q:"Did anyone ask you to share the screen to fix the wallet?",path:"Control Center -> Screen Mirroring. Decline helpers.",yes:"C"},
{id:"profile",q:"Did anyone send a settings profile file (.mobileconfig)?",path:"Mail / Files / Safari downloads. Do not install.",yes:"C"}
]},
android:{key:"35-iris-android-v2",nextC:"Stop. Remove unknown device / admin / accessibility YOURSELF. Open myaccount.google.com/security on this phone.",qs:[
{id:"gdev",q:"Google account -> Devices: a phone or browser you do not own?",path:"Settings -> Google -> Manage account -> Security -> Your devices",yes:"C"},
{id:"admin",q:"A device-admin app you did not grant?",path:"Settings -> Security -> Device admin apps",yes:"C"},
{id:"acc",q:"An Accessibility service you did not install?",path:"Settings -> Accessibility",yes:"C"},
{id:"special",q:"Display-over-apps or install-unknown-apps you did not allow?",path:"Settings -> Apps -> Special app access",yes:"B"},
{id:"chat",q:"A second phone linked to WhatsApp / Telegram?",path:"WhatsApp -> Settings -> Linked devices",yes:"C"},
{id:"fwd",q:"Gmail forwarding or a filter you did not set?",path:"Gmail -> Settings -> Forwarding and filters",yes:"C"},
{id:"apk",q:"Did someone send an APK or a cleaner to check the phone?",path:"Do not install. That is the intermediary.",yes:"C"},
{id:"notif",q:"Notification access for an app you do not know?",path:"Settings -> Apps -> Special app access -> Notification access",yes:"B"}
]}
};
function loadState(key){try{return JSON.parse(localStorage.getItem(key)||"{}");}catch(e){return {};}}
function saveState(key,s){try{localStorage.setItem(key,JSON.stringify(s));}catch(e){}}
function rank(track,answers){var cls="A",notes=[];track.qs.forEach(function(item){var a=answers[item.id];if(!a){if(cls==="A")cls="B";notes.push(item.id+": unanswered");return;}if(a==="yes"){if(item.yes==="C")cls="C";else if(cls==="A")cls="B";notes.push(item.id+": YES");}else if(a==="idk"){if(cls==="A")cls="B";notes.push(item.id+": open the path");}else notes.push(item.id+": no");});return{cls:cls,notes:notes};}
function nextText(track,cls){if(cls==="A")return "Looks quiet from what you tapped. Record the date. Do not install a cleaner.";if(cls==="B")return "Open the yellow paths. A name you cannot explain = treat as C.";return track.nextC;}
function renderTrack(name){var track=TRACKS[name],root=document.getElementById(name);if(!root||!track)return;var answers=(loadState(track.key).answers)||{};var html="";track.qs.forEach(function(item){var cur=answers[item.id]||"";html+="<div class='card'><p class='path'>"+item.path+"</p><p class='q'>"+item.q+"</p><div class='ans'>";["no","yes","idk"].forEach(function(v){var label=v==="idk"?"not sure":v;var on=cur===v?(" on-"+v):"";html+="<button type='button' data-track='"+name+"' data-id='"+item.id+"' data-v='"+v+"' class='"+on.trim()+"'>"+label+"</button>";});html+="</div></div>";});var r=rank(track,answers);html+="<div class='card'><span class='badge "+r.cls+"'>CLASS "+r.cls+"</span><p class='rule'>"+nextText(track,r.cls)+"\n"+r.notes.join("\n")+"</p><div class='row'><button class='ghost' type='button' id='reset-"+name+"'>Reset answers</button></div></div>";root.innerHTML=html;root.querySelectorAll(".ans button").forEach(function(b){b.onclick=function(){var t=TRACKS[b.getAttribute("data-track")];var s=loadState(t.key);s.answers=s.answers||{};s.answers[b.getAttribute("data-id")]=b.getAttribute("data-v");s.updated=new Date().toISOString();saveState(t.key,s);renderTrack(name);};});var reset=document.getElementById("reset-"+name);if(reset)reset.onclick=function(){saveState(track.key,{answers:{},updated:new Date().toISOString()});renderTrack(name);};}
function showTab(id){["iphone","android","sig"].forEach(function(n){var p=document.getElementById(n),b=document.getElementById("tab-"+n);if(p)p.classList.toggle("on",n===id);if(b)b.classList.toggle("on",n===id);});var line=document.getElementById("ai-line");if(line){if(id==="iphone")line.textContent="IRIS: open each green path on the iPhone. Answer what you see.";if(id==="android")line.textContent="IRIS: open each green path on Android / Google. Answer what you see.";if(id==="sig")line.textContent="IRIS: paste a PUBLIC hash only. Solana, Bitcoin, or Ethereum.";}}
var tabI=document.getElementById("tab-iphone"),tabA=document.getElementById("tab-android"),tabS=document.getElementById("tab-sig");
if(tabI)tabI.onclick=function(){showTab("iphone");};
if(tabA)tabA.onclick=function(){showTab("android");};
if(tabS)tabS.onclick=function(){showTab("sig");};
document.querySelectorAll(".ask button").forEach(function(b){b.onclick=function(){var go=b.getAttribute("data-go");if(go==="sig")showTab("sig");else showTab("iphone");};});
renderTrack("iphone");renderTrack("android");
var ALLOW={"11111111111111111111111111111111":"System","TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA":"SPL Token","TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb":"Token-2022","ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL":"ATA","ComputeBudget111111111111111111111111111111":"ComputeBudget","MemoSq4gqABAXKb96qnH8TysNcWxMyWCqXgDLGmfcHr":"Memo"};
var MAX="18446744073709551615";
var ETH_MAX="ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff";
var SOL_RPC=["https://api.mainnet-beta.solana.com","https://solana-rpc.publicnode.com"];
function looksSecret(s){var t=s.trim();if(/\b(\w+\s+){11,23}\w+\b/.test(t)&&t.split(/\s+/).length<=24)return true;if(/^\s*\[[\d,\s]{80,}\]\s*$/.test(t))return true;if(/^0x[0-9a-fA-F]{64}$/.test(t)&&false)return false;return false;}
function kindOf(s){var t=s.trim();if(/^0x[0-9a-fA-F]{64}$/.test(t))return "eth";if(/^[0-9a-fA-F]{64}$/.test(t))return "btc";if(/^[1-9A-HJ-NP-Za-km-z]{64,88}$/.test(t))return "sol";return "";}
function show(cls,text){var out=document.getElementById("out");if(!out)return;out.classList.add("on");var badge=document.getElementById("badge");badge.className="badge "+cls;badge.textContent=cls==="X"?"BLOCKED":"CLASS "+cls;document.getElementById("report").textContent=text;}
function ixList(tx){var outer=tx.transaction.message.instructions||[];var inner=[];(tx.meta&&tx.meta.innerInstructions||[]).forEach(function(g){(g.instructions||[]).forEach(function(ix){inner.push(ix);});});return outer.concat(inner);}
function classifySol(tx){var ixs=ixList(tx),programs=[],notes=[],cls="A";ixs.forEach(function(ix){var pid=String(ix.programId||"");var name=ALLOW[pid]||"UNKNOWN";if(programs.indexOf(name==="UNKNOWN"?pid:name)<0)programs.push(name==="UNKNOWN"?pid.slice(0,8)+"...":name);if(!ALLOW[pid]&&pid.length>20){cls="C";notes.push("unknown program");}var parsed=ix.parsed||null;var typ=parsed&&parsed.type?parsed.type:"";var info=parsed&&parsed.info?parsed.info:{};var amt=info.amount||(info.tokenAmount&&info.tokenAmount.amount);if(typ==="approve"||typ==="approveChecked"){if(String(amt)===MAX){if(cls!=="C")cls="B";notes.push("unlimited approve");}else notes.push("finite approve");}if(typ==="setAuthority"){cls="C";notes.push("SetAuthority");}});if(!ixs.length){cls="C";notes.push("no instructions");}return{cls:cls,programs:programs,notes:notes};}
async function solTx(sig){var body=JSON.stringify({jsonrpc:"2.0",id:1,method:"getTransaction",params:[sig,{encoding:"jsonParsed",maxSupportedTransactionVersion:0}]});var last=null;for(var i=0;i<SOL_RPC.length;i++){try{var res=await fetch(SOL_RPC[i],{method:"POST",headers:{"content-type":"application/json"},body:body});var j=await res.json();if(j.result)return j.result;last=(j.error&&j.error.message)||"empty";}catch(e){last=String(e.message||e);}}throw new Error(last||"sol rpc");}
async function btcTx(id){var res=await fetch("https://mempool.space/api/tx/"+id);if(!res.ok)throw new Error("btc lookup failed");return res.json();}
async function ethTx(hash){var body=JSON.stringify({jsonrpc:"2.0",id:1,method:"eth_getTransactionByHash",params:[hash]});var res=await fetch("https://ethereum.publicnode.com",{method:"POST",headers:{"content-type":"application/json"},body:body});var j=await res.json();if(!j.result)throw new Error((j.error&&j.error.message)||"eth empty");return j.result;}
function classifyBtc(tx){var notes=[],cls="A";var vins=(tx.vin||[]).length,vouts=tx.vout||[];notes.push("inputs "+vins+" outputs "+vouts.length);vouts.forEach(function(o,i){notes.push("out"+i+" "+(o.value||0)+" sat -> "+((o.scriptpubkey_address)||o.scriptpubkey_type||"?"));});if(vouts.length>4){if(cls==="A")cls="B";notes.push("many outputs — look at each address");}if(!vouts.length)cls="C";return{cls:cls,notes:notes};}
function classifyEth(tx){var notes=[],cls="A";var to=tx.to||"(contract create)";var data=(tx.input||"0x").toLowerCase();var val=tx.value||"0x0";notes.push("to "+to);notes.push("value "+val);if(data&&data!=="0x"){notes.push("input "+data.slice(0,10));if(data.indexOf("0x095ea7b3")===0){var tail=data.slice(-64);if(tail===ETH_MAX){cls="B";notes.push("unlimited ERC-20 approve");}else{if(cls==="A")cls="B";notes.push("ERC-20 approve");}}else{cls="C";notes.push("contract call — unknown method. Do not sign twins.");}}return{cls:cls,notes:notes};}
var run=document.getElementById("run");
if(run)run.onclick=async function(){var raw=document.getElementById("q").value||"";if(/\b(\w+\s+){11,23}\w+\b/.test(raw.trim())){show("X","Rejected. Looks like a seed.");document.getElementById("q").value="";return;}var k=kindOf(raw);if(!k){show("X","Need a public Solana signature, Bitcoin txid, or Ethereum 0x hash.");return;}show("X","Reading chain...");try{if(k==="sol"){var tx=await solTx(raw.trim());if(!tx){show("C","Not found on Solana.");return;}var r=classifySol(tx);var lines=["chain SOL","programs "+(r.programs.join(", ")||"none")].concat(r.notes.map(function(n){return "- "+n;}));show(r.cls,lines.join("\n"));}
else if(k==="btc"){var bt=await btcTx(raw.trim());var rb=classifyBtc(bt);var lb=["chain BTC"].concat(rb.notes.map(function(n){return "- "+n;}));if(rb.cls==="B")lb.push("next: confirm every output address in YOUR wallet history");show(rb.cls,lb.join("\n"));}
else {var et=await ethTx(raw.trim());var re=classifyEth(et);var le=["chain ETH"].concat(re.notes.map(function(n){return "- "+n;}));if(re.cls==="B")le.push("next: revoke the spender in YOUR wallet");if(re.cls==="C")le.push("next: do not sign twins");show(re.cls,le.join("\n"));}
}catch(e){show("C","Lookup blocked ("+e.message+"). Mail only a public hash if you write later.");}};
var clr=document.getElementById("clr");
if(clr)clr.onclick=function(){document.getElementById("q").value="";document.getElementById("out").classList.remove("on");};
